import Link from "next/link";
import { ArrowUpRight, Heart, MessageCircle, MessageSquareText, PenLine, Sparkles } from "lucide-react";
import { CinematicPage } from "@/components/motion/cinematic-page";
import { listForumCategories, listRecentTopics } from "@/lib/forum/service";

export default async function ForumPage() {
  const [categories, topics] = await Promise.all([listForumCategories().catch(() => []), listRecentTopics().catch(() => [])]);
  return <CinematicPage className="forum-page-shell mx-auto w-full max-w-7xl px-4 pb-20 pt-28 sm:px-6 lg:px-8">
    <header className="forum-feed-header"><div><p className="eyebrow">CỘNG ĐỒNG EDOLAS</p><h1 className="mt-3 font-pixel text-2xl leading-relaxed text-white sm:text-4xl">Nơi câu chuyện bắt đầu.</h1><p className="mt-3 max-w-2xl text-[#94A3B8]">Chia sẻ mẹo chơi, tìm đồng đội và cùng xây dựng cộng đồng Minecraft thân thiện.</p></div><Link href="/forum/new" className="server-button px-5 py-3 focus-ring"><PenLine className="h-4 w-4" /> Tạo bài viết</Link></header>
    <div className="forum-feed-layout mt-10"><aside className="forum-side-column"><section className="forum-modern-card"><p className="eyebrow">KHÁM PHÁ</p><h2 className="mt-2 text-xl font-bold text-white">Chuyên mục</h2><div className="mt-5 space-y-2">{categories.map((category) => <Link key={category.id} href={`#category-${category.slug}`} className="forum-category-link"><MessageSquareText className="h-4 w-4" /><span><b>{category.title}</b><small>{category.topics} chủ đề</small></span><ArrowUpRight className="ml-auto h-4 w-4" /></Link>)}</div></section><section className="forum-modern-card mt-4"><Sparkles className="h-5 w-5 text-[#67E8F9]" /><h2 className="mt-3 font-bold text-white">Chia sẻ điều tử tế</h2><p className="mt-2 text-sm leading-6 text-[#94A3B8]">Nội dung hữu ích, tôn trọng và không spam giúp feed luôn đáng đọc.</p></section></aside>
      <main className="forum-feed-column"><div className="forum-feed-toolbar"><div><p className="eyebrow">BẢNG TIN</p><h2 className="mt-2 text-2xl font-bold text-white">Bài viết mới nhất</h2></div><span className="forum-live-pill"><i /> Cộng đồng đang hoạt động</span></div>{topics.length ? topics.map((topic) => <article key={topic.id} className="forum-modern-card forum-post-card"><div className="flex items-start justify-between gap-4"><div><span className="forum-post-category">{topic.category}</span><h3 className="mt-3 text-lg font-bold text-white"><Link href={`/forum/${topic.id}`} className="hover:text-[#67E8F9]">{topic.title}</Link></h3></div><Link href={`/forum/${topic.id}`} aria-label={`Mở bài viết ${topic.title}`} className="forum-icon-button"><ArrowUpRight className="h-5 w-5" /></Link></div><p className="mt-3 text-sm text-[#94A3B8]">Đăng bởi <span className="text-[#CBD5E1]">{topic.author ?? "Thành viên"}</span></p><div className="forum-post-meta"><span><MessageCircle className="h-4 w-4" /> {topic.replies} bình luận</span><span><Heart className="h-4 w-4" /> {topic.likes} lượt thích</span></div></article>) : <div className="forum-modern-card p-10 text-center text-[#94A3B8]">Chưa có bài viết nào. Hãy mở cuộc trò chuyện đầu tiên.</div>}</main>
      <aside className="forum-side-column"><section className="forum-modern-card"><p className="eyebrow">GỢI Ý</p><h2 className="mt-2 text-xl font-bold text-white">Tham gia cộng đồng</h2><div className="forum-stat-row"><span>Bài viết mới</span><b>{topics.length}</b></div><div className="forum-stat-row"><span>Chuyên mục</span><b>{categories.length}</b></div><Link href="/forum/new" className="mt-5 flex w-full items-center justify-center gap-2 border border-[#38BDF8]/30 px-4 py-3 text-sm font-bold text-[#67E8F9] transition hover:bg-[#38BDF8]/10">Bắt đầu chia sẻ <ArrowUpRight className="h-4 w-4" /></Link></section></aside>
    </div>
  </CinematicPage>;
}
