import { NextResponse } from "next/server.js";
import type { PublicUser } from "../auth/service.ts";
import { getRequestUser as resolveUser, isStaff } from "../community/session-user.ts";
import { createWikiCluster, createWikiPage, deleteWikiCluster, deleteWikiPage, updateWikiCluster, updateWikiPage } from "./service.ts";
import { parseWikiCluster, parseWikiPage, type WikiClusterInput, type WikiPageInput } from "./validation.ts";
import { setContentTrashState } from "../admin/service.ts";

type Deps = { getRequestUser?: (r:Request)=>Promise<PublicUser|null>; createWikiCluster?: (i:WikiClusterInput)=>Promise<number>; updateWikiCluster?: (id:number,i:WikiClusterInput)=>Promise<void>; deleteWikiCluster?: typeof deleteWikiCluster; createWikiPage?: typeof createWikiPage; updateWikiPage?: (id:number,i:WikiPageInput)=>Promise<void>; deleteWikiPage?: (id:number)=>Promise<void> };
const fail=(status:number,error:string)=>NextResponse.json({ok:false,error},{status});
async function staff(request:Request,deps:Deps){const user=await(deps.getRequestUser??resolveUser)(request);if(!user)return {response:fail(401,"Bạn cần đăng nhập.")};if(!isStaff(user))return {response:fail(403,"Chỉ staff được quản trị Wiki.")};return {user};}
function idOf(raw:string){const id=Number(raw);return Number.isInteger(id)&&id>0?id:null;}
export function createWikiClusterPostHandler(deps:Deps={}){return async(request:Request)=>{const auth=await staff(request,deps);if("response"in auth)return auth.response;const parsed=parseWikiCluster(await request.json().catch(()=>null));if(!parsed.ok)return fail(400,parsed.error);try{const id=await(deps.createWikiCluster??createWikiCluster)(parsed.value);return NextResponse.json({ok:true,id},{status:201});}catch{return fail(409,"Slug cụm đã tồn tại.");}}}
export function createWikiClusterItemHandler(deps:Deps={}){return async(request:Request,{params}:{params:{id:string}})=>{const auth=await staff(request,deps);if("response"in auth)return auth.response;const id=idOf(params.id);if(!id)return fail(400,"Mã cụm không hợp lệ.");if(request.method==="DELETE"){const result=await(deps.deleteWikiCluster??deleteWikiCluster)(id);return result.ok?NextResponse.json(result):fail(result.status,result.error);}const parsed=parseWikiCluster(await request.json().catch(()=>null));if(!parsed.ok)return fail(400,parsed.error);await(deps.updateWikiCluster??updateWikiCluster)(id,parsed.value);return NextResponse.json({ok:true});}}
export function createWikiPagePostHandler(deps:Deps={}){return async(request:Request)=>{const auth=await staff(request,deps);if("response"in auth)return auth.response;const parsed=parseWikiPage(await request.json().catch(()=>null));if(!parsed.ok)return fail(400,parsed.error);try{const result=await(deps.createWikiPage??createWikiPage)(auth.user.id,parsed.value);return result.ok?NextResponse.json(result,{status:201}):fail(result.status,result.error);}catch{return fail(409,"Slug bài Wiki đã tồn tại hoặc cụm không hợp lệ.");}}}
export function createWikiPageItemHandler(deps:Deps={}){return async(request:Request,{params}:{params:{id:string}})=>{const auth=await staff(request,deps);if("response"in auth)return auth.response;const id=idOf(params.id);if(!id)return fail(400,"Mã bài không hợp lệ.");if(request.method==="DELETE"){if(deps.deleteWikiPage)await deps.deleteWikiPage(id);else await setContentTrashState(auth.user,"wiki",id,true);return NextResponse.json({ok:true});}const parsed=parseWikiPage(await request.json().catch(()=>null));if(!parsed.ok)return fail(400,parsed.error);await(deps.updateWikiPage??updateWikiPage)(id,parsed.value);return NextResponse.json({ok:true});}}
