import { NextResponse } from "next/server.js";
import type { PublicUser } from "../auth/service.ts";
import { getRequestUser as resolveUser } from "../community/session-user.ts";
import { createForumComment, createTopic, deleteForumComment, deleteTopic, shareTopic, toggleCommentLike, toggleTopicLike } from "./service.ts";
import { parseForumComment, parseNewTopic } from "./validation.ts";

type Deps = { getRequestUser?: (request: Request) => Promise<PublicUser | null>; createTopic?: typeof createTopic; toggleTopicLike?: typeof toggleTopicLike; createForumComment?: typeof createForumComment; toggleCommentLike?: typeof toggleCommentLike; shareTopic?: typeof shareTopic; deleteTopic?: typeof deleteTopic; deleteForumComment?: typeof deleteForumComment };
const fail = (status: number, error: string) => NextResponse.json({ ok: false, error }, { status });
const userOf = (request: Request, deps: Deps) => (deps.getRequestUser ?? resolveUser)(request);
const idOf = (params: { id: string }) => Number(params.id);
export function createTopicHandler(deps: Deps = {}) { return async (request: Request) => { const user = await userOf(request, deps); if (!user) return fail(401, "Bạn cần đăng nhập để đăng bài."); const parsed = parseNewTopic(await request.json().catch(() => null)); if (!parsed.ok) return fail(400, parsed.error); const result = await (deps.createTopic ?? createTopic)(user.id, parsed.value); return result.ok ? NextResponse.json(result, { status: 201 }) : fail(result.status, result.error); }; }
export function createTopicLikeHandler(deps: Deps = {}) { return async (request: Request, { params }: { params: { id: string } }) => { const user = await userOf(request, deps); if (!user) return fail(401, "Bạn cần đăng nhập để thích bài viết."); const id = idOf(params); if (!Number.isInteger(id) || id < 1) return fail(400, "Mã bài viết không hợp lệ."); const result = await (deps.toggleTopicLike ?? toggleTopicLike)(id, user.id); return result.ok ? NextResponse.json(result) : fail(result.status, result.error); }; }
export function createCommentHandler(deps: Deps = {}) { return async (request: Request, { params }: { params: { id: string } }) => { const user = await userOf(request, deps); if (!user) return fail(401, "Bạn cần đăng nhập để bình luận."); const topicId = idOf(params); const parsed = parseForumComment(await request.json().catch(() => null)); if (!Number.isInteger(topicId) || topicId < 1 || !parsed.ok) return fail(400, parsed.ok ? "Mã bài viết không hợp lệ." : parsed.error); const result = await (deps.createForumComment ?? createForumComment)(topicId, user.id, parsed.value); return result.ok ? NextResponse.json(result, { status: 201 }) : fail(result.status, result.error); }; }
export function createCommentLikeHandler(deps: Deps = {}) { return async (request: Request, { params }: { params: { id: string } }) => { const user = await userOf(request, deps); if (!user) return fail(401, "Bạn cần đăng nhập để thích bình luận."); const id = idOf(params); if (!Number.isInteger(id) || id < 1) return fail(400, "Mã bình luận không hợp lệ."); const result = await (deps.toggleCommentLike ?? toggleCommentLike)(id, user.id); return result.ok ? NextResponse.json(result) : fail(result.status, result.error); }; }
export function createShareHandler(deps: Deps = {}) { return async (request: Request, { params }: { params: { id: string } }) => { const user = await userOf(request, deps); if (!user) return fail(401, "Bạn cần đăng nhập để ghi nhận lượt chia sẻ."); const result = await (deps.shareTopic ?? shareTopic)(idOf(params)); return result.ok ? NextResponse.json(result) : fail(result.status, result.error); }; }
export function createDeleteTopicHandler(deps: Deps = {}) { return async (request: Request, { params }: { params: { id: string } }) => { const user = await userOf(request, deps); if (!user) return fail(401, "Bạn cần đăng nhập."); const result = await (deps.deleteTopic ?? deleteTopic)(idOf(params), user.id); return result.ok ? NextResponse.json(result) : fail(result.status, result.error); }; }
export function createDeleteCommentHandler(deps: Deps = {}) { return async (request: Request, { params }: { params: { id: string } }) => { const user = await userOf(request, deps); if (!user) return fail(401, "Bạn cần đăng nhập."); const result = await (deps.deleteForumComment ?? deleteForumComment)(idOf(params), user.id); return result.ok ? NextResponse.json(result) : fail(result.status, result.error); }; }
