CREATE DATABASE IF NOT EXISTS edolas_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'sa'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON edolas_db.* TO 'sa'@'%';
FLUSH PRIVILEGES;
