"use client";

import { LogOut, Search } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { AdminSession } from "@/lib/admin/sessions";
import { controlFetch } from "@/lib/control/client";

export function AdminSessionTable({ sessions, filters }: { sessions: AdminSession[]; filters: { query: string; kind: string } }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  async function revoke(session: AdminSession) { if (!window.confirm(`Thu hồi phiên ${session.kind} của @${session.username}?`)) return; const key = `${session.kind}:${session.id}`; setBusy(key); setMessage(""); try { const response = await controlFetch(`/api/control/sessions/${session.kind}/${session.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage("Đã thu hồi phiên đăng nhập."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể thu hồi phiên."); } finally { setBusy(""); } }
  return <div className="space-y-4"><form className="grid gap-3 border border-[#38BDF8]/15 bg-[#0D1225] p-4 sm:grid-cols-[1fr_220px_auto]"><label className="relative"><span className="sr-only">Tìm người dùng</span><Search className="absolute left-3 top-3.5 size-4 text-[#94A3B8]" aria-hidden="true" /><input name="query" defaultValue={filters.query} placeholder="Tìm username hoặc tên..." className="h-11 w-full border border-[#38BDF8]/20 bg-[#080B18] pl-10 pr-3 text-[#F8FAFC] focus-ring" /></label><label><span className="sr-only">Loại phiên</span><select name="kind" defaultValue={filters.kind} className="h-11 w-full border border-[#38BDF8]/20 bg-[#080B18] px-3 text-[#F8FAFC] focus-ring"><option value="all">Mọi loại phiên</option><option value="website">Website</option><option value="control">Control</option></select></label><button className="server-button px-5">Lọc phiên</button></form><p role="status" className="min-h-5 text-sm text-[#E0F2FE]">{message || `${sessions.length} phiên đang hoạt động.`}</p><div className="overflow-x-auto border border-[#38BDF8]/15"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#11162A] text-xs uppercase text-[#94A3B8]"><tr><th className="p-4">Tài khoản</th><th className="p-4">Kênh</th><th className="p-4">Hoạt động gần nhất</th><th className="p-4">Hết hạn</th><th className="p-4 text-right">Kiểm soát</th></tr></thead><tbody className="divide-y divide-[#38BDF8]/10 bg-[#0A0F20]">{sessions.map((session) => <tr key={`${session.kind}-${session.id}`}><td className="p-4"><strong className="block text-[#F8FAFC]">{session.displayName}</strong><span className="text-xs text-[#94A3B8]">@{session.username} · {session.roleName}</span></td><td className="p-4"><span className="border border-[#38BDF8]/20 px-2 py-1 text-xs uppercase text-[#67E8F9]">{session.kind}</span></td><td className="p-4 tabular-nums text-[#94A3B8]">{new Date(session.lastUsedAt).toLocaleString("vi-VN")}</td><td className="p-4 tabular-nums text-[#94A3B8]">{new Date(session.expiresAt).toLocaleString("vi-VN")}</td><td className="p-4 text-right"><button type="button" disabled={busy === `${session.kind}:${session.id}`} onClick={() => revoke(session)} className="control-topbar-link is-danger focus-ring"><LogOut className="size-4" aria-hidden="true" />{busy === `${session.kind}:${session.id}` ? "Đang thu hồi..." : "Thu hồi phiên"}</button></td></tr>)}</tbody></table>{!sessions.length ? <p className="p-10 text-center text-[#94A3B8]">Không có phiên phù hợp với bộ lọc.</p> : null}</div></div>;
}
